services:
  vite:
    image: node:latest
    working_dir: /app
    volumes:
      - ./code:/app
    expose:
      - "3000"
      - "5000"
    ports:
      - "3000:3000"
      - "5000:5000"
    command: "yarn dev --host 0.0.0.0 --port 3000"
    tty: true